apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodeapp
    image: tchibatron/awstrain:latest
    ports:
    - containerPort: 8080
  imagePullSecrets:
    - name: regcred